[package]
name = "pheasant"
version = "0.1.0"
edition = "2024"

[[example]]
path = "examples/basic"
name = "basic"

[workspace]
members = [
	"crates/pheasant_prologue",
	"crates/pheasant_uri",
	"crates/pheasant_services",
	"crates/pheasant_socket",
	"crates/pheasant_sys",
]
resolver = "3"
exclude = ["examples/basic"]

[dependencies]
pheasant_prologue = { version = "0.1.0", path = "crates/pheasant_prologue" }
pheasant_uri = { version = "0.1.0", path = "crates/pheasant_uri" }
pheasant_services = { version = "0.1.0", path = "crates/pheasant_services" }
pheasant_socket = { version = "0.1.0", path = "crates/pheasant_socket" }
# crossbeam-utils = "0.8.21"
# uuid = "1.18.1"
# rayon = "1.11.0"
# hashbrown = { workspace = true, features = ["serde"] }
# chrono.workspace = true
# embedded-io = "0.6.1"
# tokio = { workspace = true, features = ["full"] }
# bb8 = "0.9.0"
