[package]
name = "pheasant"
version = "0.1.0"
edition = "2024"

# [[example]]
# name = "hello_web"
### crate example - run like this 
### cargo run --manifest-path examples/hello-web/Cargo.toml

[workspace]
members = [
	"crates/pheasant-http",
	"crates/pheasant-uri",
	"crates/pheasant-services",
	"crates/pheasant-socket",
	"crates/pheasant-sys",
]
resolver = "3"
exclude = ["examples/basic"]

[dependencies]
pheasant-http = { version = "0.1.0", path = "crates/pheasant-http" }
pheasant-uri = { version = "0.1.0", path = "crates/pheasant-uri" }
pheasant-services = { version = "0.1.0", path = "crates/pheasant-services" }
pheasant-socket = { version = "0.1.0", path = "crates/pheasant-socket" }
# crossbeam-utils = "0.8.21"
# uuid = "1.18.1"
# rayon = "1.11.0"
# hashbrown = { workspace = true, features = ["serde"] }
# chrono.workspace = true
# embedded-io = "0.6.1"
# tokio = { workspace = true, features = ["full"] }
# bb8 = "0.9.0"
