[package]
name = "pheasant"
version = "0.1.0"
edition = "2024"

# [[example]]
# name = "hello_web"
### crate example - run like this 
### cargo run --manifest-path examples/hello-web/Cargo.toml

[workspace]
members = [
	"crates/pheasant_prologue",
	"crates/pheasant_uri",
	"crates/pheasant_services",
	"crates/pheasant_socket",
	"crates/pheasant_sys",
]
resolver = "3"
exclude = ["examples/basic"]

[dependencies]
pheasant_prologue = { version = "0.1.0", path = "crates/pheasant-prologue" }
pheasant_uri = { version = "0.1.0", path = "crates/pheasant-uri" }
pheasant_services = { version = "0.1.0", path = "crates/pheasant-services" }
pheasant_socket = { version = "0.1.0", path = "crates/pheasant-socket" }
# crossbeam-utils = "0.8.21"
# uuid = "1.18.1"
# rayon = "1.11.0"
# hashbrown = { workspace = true, features = ["serde"] }
# chrono.workspace = true
# embedded-io = "0.6.1"
# tokio = { workspace = true, features = ["full"] }
# bb8 = "0.9.0"
