[package]
name = "pheasant_message"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono.workspace = true
deflate = { workspace = true, features = ["gzip"] }
embedded-io = "0.6.1"
hashbrown.workspace = true
mime.workspace = true
pheasant_core = { version = "0.1.0", path = "../pheasant_core" }
pheasant_headers = { workspace = true }
pheasant_uri = { version = "0.1.0", path = "../pheasant_uri" }
uuid = { version = "1.18.1", features = ["v4", "v6", "v8"] }
