[package]
name = "pheasant_services"
version = "0.1.0"
edition = "2024"

[[test]]
name = "net_reset"
path = "tests/connection_reset"

[dependencies]
# bb8 = "0.9.0"
# bb8-postgres = "0.9.0"
chrono = { version = "0.4.41", features = ["serde"] }
hashbrown = "0.16.0"
mime = "0.3.17"
pheasant_http = { version = "0.1.0", path = "../pheasant_http" }
pheasant_uri = { version = "0.1.0", path = "../pheasant_uri" }
# postgres = "0.19.12"
sqlite = "0.37.0"
# uuid = { version = "1.18.1", features = ["v4", "v6", "v8"] }
