[package]
name = "pheasant_uri"
version = "0.1.0"
edition = "2024"

# [[test]]
# name = "basic"
# path = "tests/basic.rs"

[[test]]
name = "lex"
path = "tests/lex.rs"

[[bin]]
name = "dev"
path = "src/.main.rs"

[[bench]]
name = "finder"
path = "benches/finder.rs"

[[bench]]
name = "lexer"
path = "benches/lexer.rs"

[dependencies]
hashbrown = "0.16.0"
