[package]
name = "pheasant-services"
version = "0.1.0"
edition = "2024"

[[example]]
name = "sha"
path = "examples/pswd.rs"

[[test]]
name = "net_reset"
path = "tests/connection_reset"

[dependencies]
# bb8 = "0.9.0"
# bb8-postgres = "0.9.0"
chrono = { version = "0.4.41", features = ["serde"] }
embedded-io = { version = "0.7.1", features = ["alloc"] }
hashbrown = "0.16.0"
mime = "0.3.17"
num-into-ascii = { version = "0.1.0", path = "../../../num-into-ascii" }
pheasant-http = { version = "0.1.0", path = "../pheasant-http" }
pheasant-socket = { version = "0.1.0", path = "../pheasant-socket" }
pheasant-uri = { version = "0.1.0", path = "../pheasant-uri" }
sha2 = "0.10.9"
sqlx = { version = "0.8.6", features = ["sqlite"] }
# uuid = { version = "1.18.1", features = ["v4", "v6", "v8"] }
